@startuml

class Controleur {
}

class Livre {
    String titre
    String[] auteurs[]
}

class Emprunt {
    Date debut
    Date fin
}

class Usager {
    String Nom
    String Prenom
    String MotDePass
    Role Role
}

enum Role {
    Admin
    Adherent
}

Controleur - "0..*" Livre
Controleur --- "0..*" Emprunt
Controleur -- "0..*" Usager

Usager "0.. 1" -- "0..*" Livre

(Usager, Livre) . Emprunt

Usager -- "1" Role





@enduml